"""your message

Revision ID: a64e5ee10acd
Revises: f592365888bc
Create Date: 2023-04-04 14:28:52.223963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e5ee10acd'
down_revision = 'f592365888bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_messages_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_messages_username', ['username'])

    # ### end Alembic commands ###
